name: hello-world
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
<<<<<<< HEAD
      - run: make say-hello
=======
      - run: make say-hello
>>>>>>> ef690dd (add hello-world workflow)
