name: hello-world
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: d1z3d/hexlet-my-first-workflow/main
      - run: sudo apt update
      - run: sudo apt install make
      - run: make say-hello
